### ISSUE TITLE
TypeError: errorText is not a function

### ISSUE THREAD

**Issue by mcnewbk** [gatewayapps/ims-migration#4]
When there is error executing a script, ims-migration crashes with the following error:

TypeError: errorText is not a function
    at D:\repos\ims-incidentreporting\node_modules\ims-migration\dist\helpers\logging.js:39:12
    at Array.map (native)
    at Object.error (D:\repos\ims-incidentreporting\node_modules\ims-migration\dist\helpers\logging.js:38:24)
    at onMigrationFailure (D:\repos\ims-incidentreporting\node_modules\ims-migration\dist\publish\index.js:94:21)
    at D:\repos\ims-incidentreporting\node_modules\ims-migration\dist\publish\index.js:60:14
    at D:\repos\ims-incidentreporting\node_modules\continuation-local-storage\context.js:84:17
    at D:\repos\ims-incidentreporting\node_modules\continuation-local-storage\context.js:84:17
    at tryCatcher (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\repos\ims-incidentreporting\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)

**Comment by johnmurphy01** [comment]
Approved and merged. Closing
